### ISSUE TITLE
itemsetoption.bmd

### ISSUE THREAD

**Issue by ZYC088** [VDraven/MuClientTools16#2] opened 2021-08-06 09:43 UTC
Hello, thank you for your help. I found another problem. After decryption of itemsetoption.bmd, the  attribute has a negative value， +-1

**Comment by VDraven** [comment] 2021-08-06 12:18
Hi, 
It's not a bug. -1 = (char)0xFF = (short)0xFFFF = (int)0xFFFFFFFF
-1 means no value assigned to the attribute...
Thanks for testing again.

**Closed as completed by VDraven** 2021-08-06 12:18 UTC
